---

- name: Snapshot new AMI
  ec2_ami:
    state: present
    wait: yes
    wait_timeout: "{{ami_wait_timeout}}"
    instance_id: "{{hostvars[inventory_hostname]['ec2_id']}}"
    name: "{{ami_name}}"
    region: "{{ami_region}}"
    # Version 2.0 feature:
    # tags:
    #   Service: bakery
  register: instance


- name: Show output
  debug: var=instance
