---

- name: Ensure instance is in a stopped state.
  shell: "aws ec2 describe-instance-status --instance-id {{hostvars[inventory_hostname]['ec2_id']}} --region {{ami_region}}"
  register: instance_state
  until: "instance_state.stdout.find('\"Name\": \"stopped\"') > -1"
  retries: "{{instance_state_check_retries}}"
  delay: "{{instance_state_check_delay}}"

- name: Snapshot new AMI
  ec2_ami:
    state: present
    wait: yes
    wait_timeout: "{{ami_wait_timeout}}"
    instance_id: "{{hostvars[inventory_hostname]['ec2_id']}}"
    name: "{{ami_name}}"
    region: "{{ami_region}}"
    # Version 2.0 feature:
    # tags:
    #   Service: bakery
  register: instance


- name: Show output
  debug: var=instance
