---

- hosts: localhost
  connection: local
  gather_facts: False
  pre_tasks:
  - name: Check inputs
    debug: var=instance_id
  - name: estabish playbook args
    set_fact:
      aws_environment_with_rolenames: "{{aws_environment_with_rolenames}}"
  roles:
    - config
    - bakery_common
  vars:
    cage_name: "{{cage_name}}"
    customer_name: "{{customer_name}}"
    instance_id: "{{ instance_id }}"
    region: "{{ region }}"
  tasks:
    - include: "{{ playbook_dir }}/roles/bakery_common/tasks/mkami.yml"

- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - bakery_common
  tasks:
    - include: "{{ playbook_dir }}/roles/bakery_common/tasks/rminstance.yml"
      when: delete_instance is defined and delete_instance