---

- hosts: localhost
  connection: local
  gather_facts: False
  pre_tasks:
  - name: estabish playbook args
    set_fact:
      aws_environment_with_rolenames: "{{aws_environment_with_rolenames}}"
  roles:
    - config
    - siteconfig
    - propagate_tags
  vars:
    cage_name: "{{cage_name}}"
    customer_name: "{{customer_name}}"

- hosts: tag_NucleatorCage_{{cage_name}}:&tag_NucleatorCustomer_{{customer_name}}
  user: ec2-user
  connection: local
  gather_facts: False

  roles:
    - nucleatorgroups

  tasks:
#    - name: ensure that ssh config dir exists
#      file: path="{{nucleator_ssh_config_dir}}" state=directory

    - name: generate ssh config
      bastion_ssh_config:
        dest: "{{nucleator_ssh_config_dir}}"
        identity_file: "{{ nucleator_configuration_dir}}/{{ hostvars.localhost.keypair_name }}.pem"
        user: "ec2-user"
        bastion_user: "ec2-user"

- hosts: MATCH_NUCLEATORGROUP__{{bakery_group}}:&MATCH_NUCLEATORSTACKSETINSTANCE__{{cli_stackset_instance_name}}
  roles:
    - "{{bakery_group}}_configure"
