---

- hosts: localhost
  connection: local
  gather_facts: False
  pre_tasks:
  - name: estabish playbook args
    set_fact:
      aws_environment_with_rolenames: "{{aws_environment_with_rolenames}}"
  roles:
    - config
    - siteconfig
    - propagate_tags
  vars:
    cage_name: "{{cage_name}}"
    customer_name: "{{customer_name}}"

- hosts: tag_NucleatorCage_{{cage_name}}:&tag_NucleatorCustomer_{{customer_name}}
  user: ec2-user
  connection: local
  gather_facts: False
  roles:
    - nucleatorgroups

- hosts: localhost
  gather_facts: false
  roles:
    # _configure_pre play covers any pre-requisite tasks to establish
    # comms with instances.
    # TODO: valdate that scope of activity covers all required hosts
    - "{{bakery_group}}_configure_pre"

- hosts: MATCH_NUCLEATORGROUP__{{bakery_group}}:&MATCH_NUCLEATORSTACKSETINSTANCE__{{cli_stackset_instance_name}}
  roles:
    - "{{bakery_group}}_configure"
