---

- hosts: localhost
  connection: local
  gather_facts: False
  pre_tasks:
  - name: estabish playbook args
    set_fact:
      aws_environment_with_rolenames: "{{aws_environment_with_rolenames}}"
  roles:
    - config
    - siteconfig
  vars:
    cage_name: "{{cage_name}}"
    customer_name: "{{customer_name}}"

- hosts: tag_NucleatorCage_{{cage_name}}:&tag_NucleatorCustomer_{{customer_name}}
  user: ec2-user
  connection: local
  gather_facts: False
  roles:
    - nucleatorgroups

- hosts: MATCH_NUCLEATORGROUP__{{bakery_group}}:&MATCH_NUCLEATORSTACKSETINSTANCE__{{cli_stackset_instance_name}}
  roles:
    # _publish play covers and runs on all instances to be published,
    # covers tasks required to prepare instance or publishing
    # (e.g. sysprep, clean shutdown, hostname cleansing, creds cleanup, etc.)
    - "{{bakery_group}}_prepare_instances_for_publishing"

- hosts: localhost
  gather_facts: False
  roles:
    # _publish_post runs on localhost, covers wait for readiness
    # (e.g. wait for stopped state) and ami publishing tasks
    - "{{bakery_group}}_publish"
