---

- hosts: localhost
  connection: local
  gather_facts: False
  pre_tasks:
  - name: estabish playbook args
    set_fact:
      aws_environment_with_rolenames: "{{aws_environment_with_rolenames}}"
  roles:
    - config
    - siteconfig
    - "{{bakery_group}}_provision"
  vars:
    cage_name: "{{cage_name}}"
    customer_name: "{{customer_name}}"
